// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { ListsScreen } from "@/features/reading-lists";

export default function GeneratedRoutePage() {
  return <ListsScreen />;
}
