/** The papers: titles, statuses, tags, typed relations and figure keys. */

export const SHOWCASE_PROJECT_NAME = "MSc Thesis (Showcase)";
export const SHOWCASE_PROJECT_COLOR = "#3b5b8c";

export type ShowcasePaperStatus = "to_read" | "reading" | "read" | "skimmed";

export interface ShowcasePaper {
  title: string;
  authors: string[];
  year: number;
  status: ShowcasePaperStatus;
  tags: string[];
  summary: string;
  venue?: string;
  doi?: string;
  arxiv_id?: string;
  url?: string;
  abstract?: string;
  rating?: 1 | 2 | 3 | 4 | 5;
  /** Days before the seed date the paper was finished. */
  readDaysAgo?: number;
  bibtex?: string;
}

export type ShowcaseRelation = "cites" | "extends" | "contradicts" | "similar" | "builds_on" | "uses_method";

/** [fromTitle, toTitle, relation, note?] */
export type ShowcaseRelationRow = [string, string, ShowcaseRelation, string?];

/** A figure to inline into a paper's notes: [chart kind, alt text]. */
export type ShowcaseFigure = [string, string];

export interface ShowcaseAnnotation {
  key: string;
  kind: "annotation" | "note";
  annotationType: "highlight" | "note" | "underline";
  text?: string;
  comment: string;
  color: string;
  page: string;
  tags: string[];
  annotationPosition: { pageIndex: number; rects: number[][] };
  annotationSortIndex: string;
}

/** Short titles used as keys below, so the relation table stays readable. */
const T = {
  attention: "Attention Is All You Need",
  resnet: "Deep Residual Learning for Image Recognition",
  vae: "Auto-Encoding Variational Bayes",
  betaVae: "β-VAE: Learning Basic Visual Concepts with a Constrained Variational Framework",
  vqVae: "Neural Discrete Representation Learning (VQ-VAE)",
  factorVae: "FactorVAE: Disentangling by Factorising",
  locatello: "Challenging Common Assumptions in the Unsupervised Learning of Disentangled Representations",
  gan: "Generative Adversarial Nets",
  ddpm: "Denoising Diffusion Probabilistic Models",
  gcn: "Semi-Supervised Classification with Graph Convolutional Networks",
  gat: "Graph Attention Networks",
  vgae: "Variational Graph Auto-Encoders",
  nri: "Neural Relational Inference for Interacting Systems",
  battaglia: "Relational Inductive Biases, Deep Learning, and Graph Networks",
  gnnSurvey: "A Survey on Graph Neural Networks for Knowledge Graphs",
  vaeSurvey: "A Survey on Variational Autoencoders from a Green AI Perspective",
  simclr: "A Simple Framework for Contrastive Learning of Visual Representations (SimCLR)",
  moco: "Momentum Contrast for Unsupervised Visual Representation Learning (MoCo)",
  infogan: "InfoGAN: Interpretable Representation Learning by Information Maximizing GANs",
  ours: "Your Method (Placeholder Preprint)",
  cvae: "Learning Structured Output Representation using Deep Conditional Generative Models",
  iwae: "Importance Weighted Autoencoders",
  tcvae: "Isolating Sources of Disentanglement in Variational Autoencoders",
  dipVae: "Variational Inference of Disentangled Latent Concepts from Unlabeled Observations",
  ladder: "Ladder Variational Autoencoders",
  adam: "Adam: A Method for Stochastic Optimization",
  batchnorm: "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift",
  dropout: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
  graphsage: "Inductive Representation Learning on Large Graphs",
  gin: "How Powerful are Graph Neural Networks?",
  dgi: "Deep Graph Infomax",
  sde: "Score-Based Generative Modeling through Stochastic Differential Equations",
  dsprites: "dSprites: Disentanglement Testing Sprites Dataset",
  eastwood: "A Framework for the Quantitative Evaluation of Disentangled Representations",
  byol: "Bootstrap Your Own Latent: A New Approach to Self-Supervised Learning",
  flows: "Normalizing Flows: An Introduction and Review of Current Methods",
} as const;

export const SHOWCASE_TITLES = T;

export const SHOWCASE_PAPERS: ShowcasePaper[] = [
  {
    title: T.attention,
    authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Llion Jones", "Aidan N. Gomez", "Łukasz Kaiser", "Illia Polosukhin"],
    year: 2017,
    venue: "NeurIPS",
    status: "read",
    rating: 5,
    readDaysAgo: 140,
    tags: ["transformers", "foundations", "representation-learning"],
    arxiv_id: "1706.03762",
    url: "https://arxiv.org/abs/1706.03762",
    abstract:
      "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms.",
    summary:
      "Self-attention replaces recurrence for sequence modelling. Key for our encoder baseline and citation in Ch. 2.\n\n**Why it matters here:** the graph-prior module reuses multi-head attention over neighbourhoods (see GAT), so the notation in §3.2 follows this paper.",
    bibtex:
      "@inproceedings{vaswani2017attention,\n  title={Attention is all you need},\n  author={Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, {\\L}ukasz and Polosukhin, Illia},\n  booktitle={Advances in Neural Information Processing Systems},\n  volume={30},\n  year={2017}\n}",
  },
  {
    title: T.resnet,
    authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
    year: 2016,
    venue: "CVPR",
    status: "read",
    rating: 5,
    readDaysAgo: 150,
    doi: "10.1109/CVPR.2016.90",
    arxiv_id: "1512.03385",
    tags: ["cnn", "foundations", "representation-learning"],
    summary: "Skip connections stabilise very deep nets — backbone for every encoder in the experiment sweeps.",
  },
  {
    title: T.vae,
    authors: ["Diederik P. Kingma", "Max Welling"],
    year: 2014,
    venue: "ICLR",
    status: "read",
    rating: 5,
    readDaysAgo: 160,
    tags: ["vae", "latent-variables", "generative", "foundations"],
    arxiv_id: "1312.6114",
    url: "https://arxiv.org/abs/1312.6114",
    abstract:
      "How can we perform efficient inference and learning in directed probabilistic models, in the presence of continuous latent variables with intractable posterior distributions, and large datasets? We introduce a stochastic variational inference and learning algorithm that scales to large datasets.",
    summary:
      "Foundational VAE — reparameterisation trick and ELBO objective we build on throughout Ch. 2–3.\n\n$$\\mathcal{L}(\\theta,\\phi;x) = \\mathbb{E}_{q_\\phi(z|x)}[\\log p_\\theta(x|z)] - D_{KL}(q_\\phi(z|x)\\,\\|\\,p(z))$$",
    bibtex:
      "@inproceedings{kingma2014vae,\n  title={Auto-Encoding Variational Bayes},\n  author={Kingma, Diederik P and Welling, Max},\n  booktitle={International Conference on Learning Representations},\n  year={2014}\n}",
  },
  {
    title: T.betaVae,
    authors: ["Irina Higgins", "Loïc Matthey", "Arka Pal", "Christopher Burgess", "Xavier Glorot", "Matthew Botvinick", "Shakir Mohamed", "Alexander Lerchner"],
    year: 2017,
    venue: "ICLR",
    status: "reading",
    rating: 4,
    tags: ["vae", "disentanglement", "latent-variables"],
    url: "https://openreview.net/forum?id=Sy2fzU9gl",
    summary: "β hyperparameter trades reconstruction vs. disentanglement — direct motivation for the β sweep (exp-01).",
  },
  {
    title: T.vqVae,
    authors: ["Aäron van den Oord", "Oriol Vinyals", "Koray Kavukcuoglu"],
    year: 2017,
    venue: "NeurIPS",
    status: "reading",
    rating: 4,
    tags: ["vae", "discrete-latent", "generative"],
    arxiv_id: "1711.00937",
    summary: "Vector quantisation bottleneck; compare against our continuous latent ablation.",
  },
  {
    title: T.factorVae,
    authors: ["Hyunjik Kim", "Andriy Mnih"],
    year: 2018,
    venue: "ICML",
    status: "read",
    rating: 4,
    readDaysAgo: 90,
    arxiv_id: "1802.05983",
    tags: ["vae", "disentanglement", "latent-variables"],
    summary: "Total-correlation penalty as an alternative to β scaling — cite in disentanglement related work.",
  },
  {
    title: T.locatello,
    authors: ["Francesco Locatello", "Stefan Bauer", "Mario Lucic", "Gunnar Rätsch", "Sylvain Gelly", "Bernhard Schölkopf", "Olivier Bachem"],
    year: 2019,
    venue: "ICML",
    status: "read",
    rating: 5,
    readDaysAgo: 75,
    tags: ["disentanglement", "vae", "foundations"],
    arxiv_id: "1811.12359",
    abstract:
      "We provide a sober look at recent progress in the field and challenge some common assumptions. We first theoretically show that the unsupervised learning of disentangled representations is fundamentally impossible without inductive biases on both the models and the data.",
    summary: "Impossibility result without inductive biases — motivates our graph-structured prior. **The** citation for the thesis argument.",
  },
  {
    title: T.gan,
    authors: ["Ian Goodfellow", "Jean Pouget-Abadie", "Mehdi Mirza", "Bing Xu", "David Warde-Farley", "Sherjil Ozair", "Aaron Courville", "Yoshua Bengio"],
    year: 2014,
    venue: "NeurIPS",
    status: "skimmed",
    rating: 4,
    tags: ["gan", "generative", "foundations"],
    arxiv_id: "1406.2661",
    summary: "Adversarial training baseline; contrast with amortised inference in VAE family.",
  },
  {
    title: T.ddpm,
    authors: ["Jonathan Ho", "Ajay Jain", "Pieter Abbeel"],
    year: 2020,
    venue: "NeurIPS",
    status: "to_read",
    tags: ["diffusion", "generative", "latent-variables"],
    arxiv_id: "2006.11239",
    summary: "Modern generative baseline — skim for related-work completeness.",
  },
  {
    title: T.gcn,
    authors: ["Thomas N. Kipf", "Max Welling"],
    year: 2017,
    venue: "ICLR",
    status: "read",
    rating: 5,
    readDaysAgo: 120,
    tags: ["gnn", "semi-supervised", "graph-prior"],
    arxiv_id: "1609.02907",
    summary: "Spectral GCN layer — starting point for our graph encoder ablations.",
  },
  {
    title: T.gat,
    authors: ["Petar Veličković", "Guillem Cucurull", "Arantxa Casanova", "Adriana Romero", "Pietro Liò", "Yoshua Bengio"],
    year: 2018,
    venue: "ICLR",
    status: "reading",
    rating: 4,
    tags: ["gnn", "attention", "graph-prior"],
    arxiv_id: "1710.10903",
    summary: "Attention over neighbourhood — compare to fixed graph prior in our method.",
  },
  {
    title: T.vgae,
    authors: ["Thomas N. Kipf", "Max Welling"],
    year: 2016,
    venue: "NeurIPS Workshop on Bayesian Deep Learning",
    status: "read",
    rating: 5,
    readDaysAgo: 100,
    tags: ["gnn", "vae", "graph-prior", "latent-variables"],
    arxiv_id: "1611.07308",
    summary: "VAE on graph-structured data — closest prior work to our contribution.",
  },
  {
    title: T.nri,
    authors: ["Thomas Kipf", "Ethan Fetaya", "Kuan-Chieh Wang", "Max Welling", "Richard Zemel"],
    year: 2018,
    venue: "ICML",
    status: "skimmed",
    rating: 3,
    tags: ["gnn", "latent-variables", "graph-prior"],
    arxiv_id: "1802.04687",
    summary: "Latent interaction graphs — useful analogy for citation-graph priors.",
  },
  {
    title: T.battaglia,
    authors: ["Peter W. Battaglia", "Jessica B. Hamrick", "Victor Bapst", "et al."],
    year: 2018,
    status: "read",
    rating: 4,
    readDaysAgo: 130,
    tags: ["gnn", "foundations", "representation-learning"],
    arxiv_id: "1806.01261",
    summary: "Unified view of graph nets as relational reasoning — frame for thesis intro.",
  },
  {
    title: T.gnnSurvey,
    authors: ["Wang et al."],
    year: 2022,
    status: "to_read",
    tags: ["gnn", "survey", "graph-prior"],
    summary: "Background reading for related-work section on relational inductive biases.",
  },
  {
    title: T.vaeSurvey,
    authors: ["Kingma et al."],
    year: 2021,
    status: "skimmed",
    rating: 3,
    tags: ["vae", "survey", "generative"],
    summary: "Broad VAE taxonomy — sanity-check our notation against standard definitions.",
  },
  {
    title: T.simclr,
    authors: ["Ting Chen", "Simon Kornblith", "Mohammad Norouzi", "Geoffrey Hinton"],
    year: 2020,
    venue: "ICML",
    status: "to_read",
    tags: ["contrastive", "self-supervised", "representation-learning"],
    arxiv_id: "2002.05709",
    summary: "Strong visual representations without labels — optional baseline for encoder init.",
  },
  {
    title: T.moco,
    authors: ["Kaiming He", "Haoqi Fan", "Yuxin Wu", "Saining Xie", "Ross Girshick"],
    year: 2020,
    venue: "CVPR",
    status: "to_read",
    tags: ["contrastive", "self-supervised", "cnn"],
    arxiv_id: "1911.05722",
    summary: "Dictionary queue for contrastive learning — pairs with ResNet backbone experiments.",
  },
  {
    title: T.infogan,
    authors: ["Xi Chen", "Yan Duan", "Rein Houthooft", "John Schulman", "Ilya Sutskever", "Pieter Abbeel"],
    year: 2016,
    venue: "NeurIPS",
    status: "skimmed",
    rating: 3,
    tags: ["gan", "disentanglement", "latent-variables"],
    arxiv_id: "1606.03657",
    summary: "Mutual-information disentanglement in GANs — contrast with VAE-based approaches.",
  },
  {
    title: T.ours,
    authors: ["Test PhD C"],
    year: 2026,
    status: "skimmed",
    tags: ["thesis", "graph-prior", "vae", "disentanglement"],
    summary: "Internal draft outlining our contribution — keep synced with report Ch. 3–4.",
  },
  {
    title: T.cvae,
    authors: ["Kihyuk Sohn", "Honglak Lee", "Xinchen Yan"],
    year: 2015,
    venue: "NeurIPS",
    status: "read",
    rating: 3,
    readDaysAgo: 60,
    tags: ["vae", "conditional", "latent-variables"],
    summary: "Conditional VAE — the conditioning path is what we replace with a graph prior.",
  },
  {
    title: T.iwae,
    authors: ["Yuri Burda", "Roger Grosse", "Ruslan Salakhutdinov"],
    year: 2016,
    venue: "ICLR",
    status: "read",
    rating: 4,
    readDaysAgo: 45,
    arxiv_id: "1509.00519",
    tags: ["vae", "latent-variables", "inference"],
    summary: "Tighter bound via importance sampling. Used k=5 for the held-out likelihood numbers in exp-05.",
  },
  {
    title: T.tcvae,
    authors: ["Ricky T. Q. Chen", "Xuechen Li", "Roger Grosse", "David Duvenaud"],
    year: 2018,
    venue: "NeurIPS",
    status: "read",
    rating: 5,
    readDaysAgo: 40,
    arxiv_id: "1802.04942",
    tags: ["vae", "disentanglement", "latent-variables"],
    summary: "Decomposes the KL into index-code MI, total correlation, dimension-wise KL. Defines the **MIG** metric we report.",
  },
  {
    title: T.dipVae,
    authors: ["Abhishek Kumar", "Prasanna Sattigeri", "Avinash Balakrishnan"],
    year: 2018,
    venue: "ICLR",
    status: "skimmed",
    rating: 3,
    arxiv_id: "1711.00848",
    tags: ["vae", "disentanglement"],
    summary: "Moment-matching penalty on the aggregate posterior — one more point on the β/TC axis for Table 2.",
  },
  {
    title: T.ladder,
    authors: ["Casper Kaae Sønderby", "Tapani Raiko", "Lars Maaløe", "Søren Kaae Sønderby", "Ole Winther"],
    year: 2016,
    venue: "NeurIPS",
    status: "skimmed",
    arxiv_id: "1602.02282",
    tags: ["vae", "hierarchical", "latent-variables"],
    summary: "Hierarchical latents with top-down inference — candidate for a deeper prior if time allows.",
  },
  {
    title: T.adam,
    authors: ["Diederik P. Kingma", "Jimmy Ba"],
    year: 2015,
    venue: "ICLR",
    status: "read",
    rating: 4,
    readDaysAgo: 200,
    arxiv_id: "1412.6980",
    tags: ["optimisation", "foundations"],
    summary: "Optimiser for every run. lr 1e-3, β₁ 0.9, β₂ 0.999 unless stated.",
  },
  {
    title: T.batchnorm,
    authors: ["Sergey Ioffe", "Christian Szegedy"],
    year: 2015,
    venue: "ICML",
    status: "read",
    rating: 3,
    readDaysAgo: 210,
    arxiv_id: "1502.03167",
    tags: ["cnn", "optimisation", "foundations"],
    summary: "Used in the ResNet encoder; disabled in the decoder after it hurt reconstruction (exp-02 note).",
  },
  {
    title: T.dropout,
    authors: ["Nitish Srivastava", "Geoffrey Hinton", "Alex Krizhevsky", "Ilya Sutskever", "Ruslan Salakhutdinov"],
    year: 2014,
    venue: "JMLR",
    status: "skimmed",
    tags: ["regularisation", "foundations"],
    summary: "Background only. Not used — KL already regularises the latent.",
  },
  {
    title: T.graphsage,
    authors: ["William L. Hamilton", "Rex Ying", "Jure Leskovec"],
    year: 2017,
    venue: "NeurIPS",
    status: "read",
    rating: 4,
    readDaysAgo: 55,
    arxiv_id: "1706.02216",
    tags: ["gnn", "graph-prior", "inductive"],
    summary: "Neighbourhood sampling makes the graph encoder inductive — needed so unseen papers get a latent.",
  },
  {
    title: T.gin,
    authors: ["Keyulu Xu", "Weihua Hu", "Jure Leskovec", "Stefanie Jegelka"],
    year: 2019,
    venue: "ICLR",
    status: "read",
    rating: 4,
    readDaysAgo: 30,
    arxiv_id: "1810.00826",
    tags: ["gnn", "foundations", "graph-prior"],
    summary: "WL-test expressiveness bound. Justifies sum aggregation in the graph-prior module (§3.2).",
  },
  {
    title: T.dgi,
    authors: ["Petar Veličković", "William Fedus", "William L. Hamilton", "Pietro Liò", "Yoshua Bengio", "R Devon Hjelm"],
    year: 2019,
    venue: "ICLR",
    status: "reading",
    arxiv_id: "1809.10341",
    tags: ["gnn", "self-supervised", "contrastive"],
    summary: "Mutual-information objective on graphs — bridge between the contrastive and graph clusters.",
  },
  {
    title: T.sde,
    authors: ["Yang Song", "Jascha Sohl-Dickstein", "Diederik P. Kingma", "Abhishek Kumar", "Stefano Ermon", "Ben Poole"],
    year: 2021,
    venue: "ICLR",
    status: "to_read",
    arxiv_id: "2011.13456",
    tags: ["diffusion", "generative"],
    summary: "Unifies score matching and diffusion — only for the related-work paragraph on non-VAE generative models.",
  },
  {
    title: T.dsprites,
    authors: ["Loïc Matthey", "Irina Higgins", "Demis Hassabis", "Alexander Lerchner"],
    year: 2017,
    status: "read",
    rating: 4,
    readDaysAgo: 95,
    url: "https://github.com/deepmind/dsprites-dataset",
    tags: ["dataset", "disentanglement"],
    summary: "The benchmark. 737,280 binary 64×64 images from 6 ground-truth factors. Every experiment here runs on it.",
  },
  {
    title: T.eastwood,
    authors: ["Cian Eastwood", "Christopher K. I. Williams"],
    year: 2018,
    venue: "ICLR",
    status: "read",
    rating: 4,
    readDaysAgo: 35,
    tags: ["disentanglement", "evaluation"],
    summary: "Disentanglement / completeness / informativeness (DCI). Reported next to MIG in every results table.",
  },
  {
    title: T.byol,
    authors: ["Jean-Bastien Grill", "Florian Strub", "Florent Altché", "et al."],
    year: 2020,
    venue: "NeurIPS",
    status: "to_read",
    arxiv_id: "2006.07733",
    tags: ["contrastive", "self-supervised", "representation-learning"],
    summary: "Contrastive learning without negatives — parked with SimCLR/MoCo as an encoder-init option.",
  },
  {
    title: T.flows,
    authors: ["Ivan Kobyzev", "Simon J.D. Prince", "Marcus A. Brubaker"],
    year: 2020,
    venue: "IEEE TPAMI",
    status: "skimmed",
    rating: 3,
    arxiv_id: "1908.09257",
    tags: ["generative", "survey", "latent-variables"],
    summary: "Survey. A flow posterior is the obvious 'future work' for a tighter bound — one paragraph in Ch. 6.",
  },
];

/** Dense enough that the default cites-only graph view shows structure. */
export const SHOWCASE_RELATIONS: ShowcaseRelationRow[] = [
  [T.ours, T.betaVae, "extends", "Graph prior generalises β-VAE"],
  [T.ours, T.vgae, "builds_on"],
  [T.ours, T.locatello, "cites", "Inductive bias argument"],
  [T.ours, T.gnnSurvey, "cites"],
  [T.ours, T.vgae, "cites"],
  [T.ours, T.vae, "cites"],
  [T.ours, T.tcvae, "uses_method", "MIG metric"],
  [T.ours, T.eastwood, "uses_method", "DCI metric"],
  [T.ours, T.dsprites, "uses_method", "Benchmark"],
  [T.ours, T.gin, "uses_method", "Sum aggregation"],
  [T.ours, T.graphsage, "builds_on", "Inductive encoder"],
  [T.betaVae, T.vae, "extends"],
  [T.betaVae, T.factorVae, "cites"],
  [T.betaVae, T.dsprites, "uses_method"],
  [T.factorVae, T.betaVae, "extends"],
  [T.factorVae, T.vae, "builds_on"],
  [T.factorVae, T.locatello, "cites"],
  [T.tcvae, T.betaVae, "extends", "Decomposes the β penalty"],
  [T.tcvae, T.factorVae, "similar", "Both penalise total correlation"],
  [T.tcvae, T.vae, "builds_on"],
  [T.dipVae, T.betaVae, "similar"],
  [T.dipVae, T.vae, "extends"],
  [T.eastwood, T.betaVae, "cites"],
  [T.eastwood, T.infogan, "cites"],
  [T.eastwood, T.dsprites, "uses_method"],
  [T.vqVae, T.vae, "extends"],
  [T.vqVae, T.resnet, "uses_method"],
  [T.vqVae, T.gan, "cites"],
  [T.cvae, T.vae, "extends"],
  [T.iwae, T.vae, "extends", "Tighter bound"],
  [T.ladder, T.vae, "extends"],
  [T.ladder, T.batchnorm, "uses_method"],
  [T.locatello, T.betaVae, "contradicts", "No free disentanglement"],
  [T.locatello, T.factorVae, "cites"],
  [T.locatello, T.tcvae, "cites"],
  [T.locatello, T.dipVae, "cites"],
  [T.locatello, T.dsprites, "uses_method"],
  [T.infogan, T.gan, "extends"],
  [T.infogan, T.betaVae, "similar"],
  [T.ddpm, T.vae, "similar"],
  [T.ddpm, T.gan, "similar"],
  [T.sde, T.ddpm, "extends"],
  [T.flows, T.vae, "cites"],
  [T.flows, T.ddpm, "cites"],
  [T.gat, T.attention, "uses_method"],
  [T.gat, T.gcn, "extends"],
  [T.gat, T.battaglia, "cites"],
  [T.vgae, T.vae, "extends"],
  [T.vgae, T.gcn, "uses_method"],
  [T.vgae, T.gat, "cites"],
  [T.nri, T.vgae, "similar"],
  [T.nri, T.gat, "uses_method"],
  [T.nri, T.battaglia, "cites"],
  [T.battaglia, T.gcn, "cites"],
  [T.battaglia, T.gat, "cites"],
  [T.graphsage, T.gcn, "extends", "Inductive, sampled neighbourhoods"],
  [T.gin, T.gcn, "contradicts", "Mean aggregation loses expressiveness"],
  [T.gin, T.graphsage, "cites"],
  [T.dgi, T.gcn, "uses_method"],
  [T.dgi, T.graphsage, "cites"],
  [T.dgi, T.simclr, "similar", "MI objective"],
  [T.gnnSurvey, T.battaglia, "cites"],
  [T.gnnSurvey, T.gin, "cites"],
  [T.gnnSurvey, T.graphsage, "cites"],
  [T.vaeSurvey, T.vae, "cites"],
  [T.vaeSurvey, T.betaVae, "cites"],
  [T.vaeSurvey, T.iwae, "cites"],
  [T.vaeSurvey, T.ladder, "cites"],
  [T.simclr, T.moco, "similar"],
  [T.simclr, T.resnet, "uses_method"],
  [T.moco, T.resnet, "uses_method"],
  [T.moco, T.simclr, "cites"],
  [T.byol, T.simclr, "extends", "Drops the negatives"],
  [T.byol, T.moco, "cites"],
  [T.attention, T.gnnSurvey, "cites"],
  [T.resnet, T.batchnorm, "uses_method"],
  [T.resnet, T.adam, "cites"],
  [T.batchnorm, T.dropout, "cites"],
  [T.gcn, T.battaglia, "cites"],
  [T.gcn, T.adam, "uses_method"],
];

export const SHOWCASE_PAPER_FIGURES: Record<string, ShowcaseFigure[]> = {
  [T.attention]: [["attention-arch", "Transformer encoder block"]],
  [T.resnet]: [["resnet-block", "Residual skip connection"]],
  [T.vqVae]: [["vqvae-codebook", "Vector quantisation codebook"]],
  [T.betaVae]: [
    ["beta-vae-heatmap", "Latent factor traversals"],
    ["beta-sweep-bar", "β vs reconstruction / disentanglement"],
  ],
  [T.gnnSurvey]: [["gnn-graph", "Graph neighbourhood"]],
  [T.ours]: [["method-overview", "Proposed pipeline"]],
};
