// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { SharedWithMeScreen } from "@/features/sharing/ui/shared-with-me-screen";

export default function GeneratedRoutePage() {
  return <SharedWithMeScreen />;
}
