// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
import { renderGeneratedRoute } from "@/deployment/render-route";

export default function GeneratedRoutePage() {
  return renderGeneratedRoute("/report");
}
