// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import dynamic from "next/dynamic";
import { ScreenLoader } from "@/components/thesis-loader";

const Screen = dynamic(() => import("@/features/report").then((m) => m.ReportScreen), {
  ssr: false,
  loading: () => <ScreenLoader status="Loading…" />,
});

export default function GeneratedRoutePage() {
  return <Screen />;
}
