// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { AiProposalReviewScreen } from "@/features/ai-assistant/ui/ai-proposal-review-screen";

export default function GeneratedRoutePage() {
  return <AiProposalReviewScreen />;
}
