// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { ReportOverleafScreen } from "@/features/report";

export default function GeneratedRoutePage() {
  return <ReportOverleafScreen />;
}
