// `java.net.URI` needs its own import: a Gradle Kotlin DSL script has no implicit
// `java.*`, so the fully-qualified `java.net.URI(appUrl)` does not resolve and the
// build fails at *configuration* with `Unresolved reference: net` — before any
// Kotlin is compiled, which is how it went unnoticed until the module was built on
// a JDK the Android plugin accepts.
import java.net.URI

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

/**
 * What the web view loads. `WEAVEFORGE_URL` at build time overrides the
 * deployed app, so a debug build can point at a laptop on the same network
 * (`WEAVEFORGE_URL=http://192.168.1.10:3000 ./gradlew assembleDebug`) — the
 * same variable the desktop shell reads.
 */
val appUrl: String = System.getenv("WEAVEFORGE_URL")?.takeIf { it.isNotBlank() }
    ?: "https://app.weaveforge.org/"

/**
 * The host and scheme of [appUrl], parsed leniently.
 *
 * Not `URI` for the host: a Gradle configuration must not throw on a URL a user
 * typed, and `URI("http://192.168.1.10:3000")` is fine but `URI("192.168.1.10")`
 * — which someone will pass — is a relative URI whose `host` is null. Parse the
 * parts and fall back rather than failing the whole build on a malformed dev URL.
 */
val appUri: URI? = runCatching { URI(appUrl) }.getOrNull()
val appHost: String = appUri?.host?.takeIf { it.isNotBlank() } ?: "app.weaveforge.org"
val appIsCleartext: Boolean = (appUri?.scheme ?: "https").lowercase() == "http"

/**
 * Hosts the WebView may load, and the ones it may then call the ink bridge from.
 *
 * The bridge is a capability granted to a *WebView*, not to an origin: a
 * `@JavascriptInterface` object is visible to every document that loads in it,
 * and Android's own lint calls untrusted content in a WebView with a JS
 * interface the most common WebView vulnerability. A default `WebViewClient`
 * has no navigation policy at all — `shouldOverrideUrlLoading` returns false,
 * meaning "load everything here" — so an OAuth redirect, a DOI link in a paper,
 * or a collaborator's `<a href>` in a shared note all become callers.
 *
 * The list is deliberately a build-time constant rather than something read from
 * the page: a policy the loaded document can influence is not a policy.
 */
val appAllowedHosts: String = buildList {
    add("app.weaveforge.org")
    // A development URL names its own host, and it is the only other one the
    // shell may ever load.
    if (appHost.isNotBlank() && appHost != "app.weaveforge.org") add(appHost)
}.joinToString(",")

/**
 * A scoped cleartext policy, generated rather than global.
 *
 * `android:usesCleartextTraffic` is one boolean for the whole application: set
 * for a `http://` development URL it permits plaintext HTTP to *every* host, so
 * a sideloaded debug APK — the workflow the README recommends — would send
 * session cookies in the clear to any host a redirect or a captive portal names.
 * The scoped tool is a network security configuration naming the development
 * host, and the Gradle side already has that host in hand.
 */
val generatedRes = layout.buildDirectory.dir("generated/networkSecurity/res")
val generateNetworkSecurityConfig by tasks.registering {
    val outDir = generatedRes
    val host = appHost
    val cleartext = appIsCleartext
    val httpsHosts = appAllowedHosts
    inputs.property("host", host)
    inputs.property("cleartext", cleartext.toString())
    outputs.dir(outDir)
    doLast {
        val xmlDir = outDir.get().asFile.resolve("xml")
        xmlDir.mkdirs()
        // Only the named development host is exempted, and only in a build that
        // asked for plaintext. Everything else is offline in the clear.
        val domainConfig = if (cleartext) {
            """
              <domain-config cleartextTrafficPermitted="true">
                <domain includeSubdomains="false">$host</domain>
              </domain-config>
            """.trimIndent()
        } else {
            ""
        }
        xmlDir.resolve("network_security_config.xml").writeText(
            """
            <?xml version="1.0" encoding="utf-8"?>
            <!--
              Generated by apps/android/app/build.gradle.kts. Do not edit by hand.

              The base config forbids cleartext everywhere; a development host is
              exempted by name, and only when the build URL was http. The
              application-wide android:usesCleartextTraffic flag this replaces
              could not express "this host only".

              Hosts the shell may load: $httpsHosts
            -->
            <network-security-config>
              <base-config cleartextTrafficPermitted="false">
                <trust-anchors>
                  <certificates src="system" />
                </trust-anchors>
              </base-config>
            $domainConfig
            </network-security-config>
            """.trimIndent() + "\n",
        )
    }
}

android {
    namespace = "org.weaveforge.ink"
    compileSdk = 35

    defaultConfig {
        applicationId = "org.weaveforge.ink"
        minSdk = 29
        targetSdk = 35
        versionCode = 1
        versionName = "0.6.0"
        buildConfigField("String", "APP_URL", "\"$appUrl\"")
        // Comma-separated. The navigation policy reads this; nothing in the page
        // can add to it.
        buildConfigField("String", "ALLOWED_HOSTS", "\"$appAllowedHosts\"")
    }

    /**
     * The release signing identity, from the environment.
     *
     * This shell is not a developer-only artifact: it is the only way to get the
     * stylus overlay, because a Trusted Web Activity runs in Chrome Custom Tabs and
     * allows no native view on top. So it needs a real release path, and a release
     * APK with no `signingConfig` is not a deliverable — `assembleRelease` produces
     * something that cannot be installed over the debug build.
     *
     * Read from the environment rather than committed, matching how `WEAVEFORGE_URL`
     * is already read by this file: a keystore is an identity, and identities do not
     * belong in a repository. The TWA's release workflow reads its keystore from CI
     * secrets; the same four names are used here so one set of secrets covers both.
     *
     * Absent the variables the release variant is simply unsigned, which is what a
     * local `-Release` build without secrets should be — a build, not a release.
     */
    signingConfigs {
        create("release") {
            val store = System.getenv("ANDROID_KEYSTORE_FILE")
            if (!store.isNullOrBlank() && file(store).exists()) {
                storeFile = file(store)
                storePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("ANDROID_KEY_ALIAS")
                keyPassword = System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildFeatures {
        buildConfig = true
    }

    sourceSets["main"].res.srcDir(generatedRes)
    tasks.named("preBuild") { dependsOn(generateNetworkSecurityConfig) }

    androidResources {
        // Windows drops `desktop.ini` into folders it has customised; the
        // resource merger refuses any file it does not understand.
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!desktop.ini:!*~"
    }

    testOptions {
        unitTests {
            // `InkGestureRouter` is deliberately free of Android types — it reads a
            // flat `GestureEvent`, not a `MotionEvent` — so its rules are a plain JVM
            // test with no emulator and no Robolectric. That matters because the
            // gesture rules are the part of this module that is hardest to debug on a
            // device and the part that has already been wrong once.
            isIncludeAndroidResources = false
            isReturnDefaultValues = true
        }
    }

    buildTypes {
        release {
            val hasSigning = System.getenv("ANDROID_KEYSTORE_FILE")
                ?.let { file(it).exists() } == true
            if (hasSigning) signingConfig = signingConfigs.getByName("release")
            // Leading `is` is AGP's Kotlin DSL accessor for the boolean setter; the
            // bare names resolve only from Java.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.webkit:webkit:1.12.1")
    // CanvasFrontBufferedRenderer: the wet stroke written straight to the scanout buffer.
    implementation("androidx.graphics:graphics-core:1.0.3")

    // The gesture rules, as a JVM test. See `InkGestureRouterTest`.
    testImplementation("junit:junit:4.13.2")
    // `org.json` is part of Android, but a JVM unit test sees only stubs of it.
    testImplementation("org.json:json:20240303")
}
