// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { LogbookScreen } from "@/features/logbook";

export default function GeneratedRoutePage() {
  return <LogbookScreen />;
}
