// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { SettingsScreen } from "@/features/settings";

export default function GeneratedRoutePage() {
  return <SettingsScreen />;
}
