// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { GitScreen } from "@/features/sync";

export default function GeneratedRoutePage() {
  return <GitScreen />;
}
