// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { WikiScreen } from "@/features/wiki";

export default function GeneratedRoutePage() {
  return <WikiScreen />;
}
