// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { DashboardScreen } from "@/features/dashboard";

export default function GeneratedRoutePage() {
  return <DashboardScreen />;
}
