/**
 * The PRISMA flow diagram, as LaTeX a report can `\input`.
 *
 * PRISMA 2020 asks a review to show how many records it found, how many it
 * threw away, and why -- the flow diagram every systematic review opens with.
 * The numbers come from `prismaCounts`, which derives them from the decisions,
 * so the figure cannot drift from the screen it describes: regenerate it and
 * the boxes follow.
 *
 * TikZ rather than an image. A figure in the report's own source recompiles at
 * the report's own font and column width, survives a change of template, and
 * diffs as text -- none of which a rendered PNG does. The cost is a `tikz`
 * dependency, which any LaTeX that compiles a thesis already has.
 */

import type { PrismaCounts } from "../../reading-lists/domain/screening.js";
import { escapeLatexText } from "./markdown-to-latex.js";

export interface PrismaFigureOptions {
  /** `\label{...}`, so the prose can `\ref` it. */
  label?: string;
  caption?: string;
  /** Exclusion reasons, as `exclusionReasons` returns them. */
  reasons?: readonly { reason: string; count: number }[];
  /** The database or register the records came from, if it is worth naming. */
  source?: string;
}

/** The packages the figure needs, for a preamble that does not have them yet. */
export const PRISMA_FIGURE_PACKAGES: readonly string[] = ["tikz", "float"];

const BOX =
  "\\tikzstyle{prismabox}=[draw, rectangle, text width=6.2cm, minimum height=1cm, align=left, inner sep=6pt]";
const ARROW = "\\tikzstyle{prismaflow}=[->, >=latex, thick]";

function line(count: number, label: string): string {
  return `${escapeLatexText(label)} (n = ${count})`;
}

/**
 * One box's text: a heading, then the counts under it.
 *
 * `\\` inside a `text width` node is a line break, and each line is escaped
 * before it goes in -- a reason typed by a reviewer is prose, and prose
 * contains the characters that end a LaTeX document.
 */
function box(name: string, heading: string, lines: readonly string[], at: string): string {
  const body = [`\\textbf{${escapeLatexText(heading)}}`, ...lines].join(" \\\\ ");
  return `  \\node[prismabox] (${name}) ${at} {${body}};`;
}

/**
 * The figure, as a string to write beside the report's other sources.
 *
 * Returned rather than written: the caller decides whether it becomes a file in
 * an Overleaf export, a block in the editor, or something to show and discard.
 */
export function prismaFigureTex(
  counts: PrismaCounts,
  options: PrismaFigureOptions = {},
): string {
  const caption = options.caption ?? "Study selection (PRISMA 2020).";
  const label = options.label ?? "fig:prisma";

  const identified = [
    line(counts.identified, options.source ? `Records from ${options.source}` : "Records identified"),
    ...(counts.duplicates ? [line(counts.duplicates, "Duplicates removed")] : []),
  ];
  const excludedReasons = (options.reasons ?? [])
    .filter((entry) => entry.reason.trim())
    .map((entry) => line(entry.count, entry.reason));

  return [
    "% Generated by WeaveForge from the screening decisions. Regenerate rather",
    "% than editing: the numbers are derived, and an edit here would be a claim",
    "% the data does not make.",
    "\\begin{figure}[H]",
    "  \\centering",
    `  ${BOX}`,
    `  ${ARROW}`,
    "  \\begin{tikzpicture}[node distance=1.4cm]",
    box("identified", "Identification", identified, ""),
    box("screened", "Screening", [line(counts.screened, "Records screened")], "[below=of identified]"),
    box(
      "screenexcluded",
      "Excluded on title and abstract",
      [line(counts.excludedAtScreening, "Records excluded")],
      "[right=1.2cm of screened]",
    ),
    box(
      "eligible",
      "Eligibility",
      [line(counts.eligible, "Full texts assessed")],
      "[below=of screened]",
    ),
    box(
      "fullexcluded",
      "Excluded at full text",
      excludedReasons.length
        ? excludedReasons
        : [line(counts.excludedAtFullText, "Full texts excluded")],
      "[right=1.2cm of eligible]",
    ),
    box("included", "Included", [line(counts.included, "Studies included")], "[below=of eligible]"),
    "    \\draw[prismaflow] (identified) -- (screened);",
    "    \\draw[prismaflow] (screened) -- (screenexcluded);",
    "    \\draw[prismaflow] (screened) -- (eligible);",
    "    \\draw[prismaflow] (eligible) -- (fullexcluded);",
    "    \\draw[prismaflow] (eligible) -- (included);",
    "  \\end{tikzpicture}",
    `  \\caption{${escapeLatexText(caption)}}`,
    `  \\label{${label}}`,
    "\\end{figure}",
    "",
  ].join("\n");
}

/**
 * What is not yet settled, in a sentence, or null when everything is.
 *
 * Shown next to the figure rather than folded into it. A diagram whose boxes
 * quietly omit forty undecided papers is worse than no diagram: it reads as
 * finished, and the reader has no way to tell that it is not.
 */
export function prismaCaveat(counts: PrismaCounts): string | null {
  const parts: string[] = [];
  if (counts.undecided) parts.push(`${counts.undecided} not yet screened`);
  if (counts.conflicts) parts.push(`${counts.conflicts} where reviewers disagree`);
  return parts.length ? `${parts.join(", ")}. The diagram counts only settled decisions.` : null;
}
