// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { VaultScreen } from "@/features/vault";

export default function GeneratedRoutePage() {
  return <VaultScreen />;
}
