// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { PlanScreen } from "@/features/plan";

export default function GeneratedRoutePage() {
  return <PlanScreen />;
}
