#!/usr/bin/env node
/**
 * The atlas page, with its figures read off the repository.
 *
 * The atlas is a designed page, not a table, so it cannot be generated whole —
 * the argument, the diagrams and the layout are written by hand in
 * `docs/atlas/atlas.template.html`. What it must not do is state a number that
 * has since moved: a reader who checks one figure and finds it wrong stops
 * trusting the page. So every figure in the template is a `{{TOKEN}}`, filled
 * here from the same counting the architecture map uses.
 *
 *   node scripts/build-atlas.mjs            rewrite docs/atlas.html
 *   node scripts/build-atlas.mjs --check    fail if it is out of date
 *
 * `--check` is what CI runs, so a change that moves one of these figures has to
 * carry the regenerated page with it.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  ROOT,
  filesUnder,
  featureSlices,
  linesUnder,
  measure,
  migrations,
  n,
  read,
  switchCases,
  webRoutes,
} from "./lib/repo-stats.mjs";

const TEMPLATE = "docs/atlas/atlas.template.html";
const OUT = "docs/atlas.html";

/** Small counts read better as words in a sentence than as digits. */
const WORDS = [
  "no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
  "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
  "seventeen", "eighteen", "nineteen", "twenty",
];
const word = (value) => WORDS[value] ?? n(value);

function values() {
  const migration = migrations();
  const routes = webRoutes();

  const relay = switchCases(
    "apps/web/src/features/ai-assistant/infrastructure/mcp-browser-relay.ts",
  );
  const proposals = relay.filter((tool) => tool.startsWith("propose_"));
  const workspaceTools = [
    ...read("apps/desktop/src/local-mcp.ts").matchAll(/name: "([a-z_]+)"/g),
  ].filter((match) => match[1] !== "weaveforge-workspace");

  const docs = measure({ dir: "docs", unit: "files" });

  return {
    CORE_LINES: n(measure({ dir: "packages/core", unit: "lines" }).lines),
    WEB_LINES: n(measure({ dir: "apps/web", unit: "lines" }).lines),
    DESKTOP_LINES: n(measure({ dir: "apps/desktop", unit: "lines" }).lines),
    DESKTOP_FILES: n(measure({ dir: "apps/desktop/src", unit: "lines" }).files),
    PITCH_LINES: n(measure({ dir: "apps/pitch", unit: "lines" }).lines),
    PYTHON_LINES: n(measure({ dir: "python/weaveforge", unit: "lines" }).lines),
    PYTHON_TEST_LINES: n(measure({ dir: "python/tests", unit: "lines" }).lines),

    CORE_SLICES: n(featureSlices("packages/core/src").length),
    WEB_SLICES: n(featureSlices("apps/web/src").length),
    WEB_PAGES: n(routes.pages),
    API_ROUTES: n(routes.apiRoutes),

    MIGRATION_COUNT: n(migration.count),
    MIGRATION_FIRST: migration.first,
    MIGRATION_LAST: migration.last,
    MIGRATION_LINES: n(migration.lines),

    SCRIPT_FILES: n(filesUnder("scripts").length),
    DOC_FILES: n(docs.files),
    DOC_LINES: n(linesUnder("docs", ".md")),

    ASSISTANT_TOOLS: n(relay.length),
    ASSISTANT_TOOLS_WORD: word(relay.length),
    ASSISTANT_READ_WORD: word(relay.length - proposals.length),
    ASSISTANT_PROPOSE_WORD: word(proposals.length),
    WORKSPACE_TOOLS: n(workspaceTools.length),
    WORKSPACE_TOOLS_WORD: word(workspaceTools.length),
  };
}

/**
 * The template is a fragment — it opens at `<title>` — because it was authored
 * to be served inside a frame that supplied the skeleton. A file in `docs/` is
 * opened directly, so it gets its own.
 */
function page(body) {
  // The template's head ends at its closing `</style>`; everything after it is
  // the page. Split there rather than wrapping the whole fragment, so the style
  // block does not end up inside the body.
  const marker = "</style>";
  const cut = body.indexOf(marker);
  if (cut < 0) throw new Error("atlas: the template has no <style> block to close the head at");
  const head = body.slice(0, cut + marker.length);
  const rest = body.slice(cut + marker.length);

  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    "<!-- Generated by scripts/build-atlas.mjs from docs/atlas/atlas.template.html.",
    "     Edit the template, then run `npm run docs:generate`. -->",
    head.trim(),
    "</head>",
    "<body>",
    rest.trim(),
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

/**
 * Every word token also gets a `_CAP` twin, because the same count opens a
 * sentence in one place and sits mid-sentence in another, and "three read"
 * capitalised by hand is a figure waiting to be forgotten.
 */
function tokens() {
  const base = values();
  const capitalised = Object.entries(base)
    .filter(([key]) => key.endsWith("_WORD"))
    .map(([key, value]) => [`${key}_CAP`, value.charAt(0).toUpperCase() + value.slice(1)]);
  return { ...base, ...Object.fromEntries(capitalised) };
}

function build() {
  // Newlines are decided once, at the end, by what the output file already
  // uses. Read the template flat: on a Windows checkout it arrives with CRLF,
  // and the conversion below then turned every one of those into \r\r\n — a
  // file that regenerated identically on Windows and differed on CI, which is
  // exactly the disagreement this generator exists to prevent.
  const template = read(TEMPLATE).replace(/\r\n/g, "\n");
  const figures = tokens();
  const filled = template.replace(/\{\{([A-Z_]+)\}\}/g, (whole, key) => {
    const value = figures[key];
    if (value === undefined) throw new Error(`atlas: no value for ${whole}`);
    return value;
  });
  const left = filled.match(/\{\{[A-Z_]+\}\}/);
  if (left) throw new Error(`atlas: ${left[0]} was not filled`);
  return page(filled);
}

const out = path.join(ROOT, OUT);
const next = build();
const current = (() => {
  try {
    return readFileSync(out, "utf8");
  } catch {
    return null;
  }
})();

// Written with the newline the file already had, so a checkout with CRLF does
// not report every line as changed.
const newline = current?.includes("\r\n") ? "\r\n" : "\n";
const text = newline === "\n" ? next : next.replace(/\n/g, "\r\n");

/**
 * The first line that differs, so a failure names the figure.
 *
 * "Out of date" alone is enough when the person reading it can run the
 * generator and look at the diff. On CI they cannot, and a figure that is
 * stale there and correct on a developer's machine leaves nothing to go on.
 */
function firstDifference(a, b) {
  const left = a.split(/\r?\n/);
  const right = b.split(/\r?\n/);
  for (let i = 0; i < Math.max(left.length, right.length); i += 1) {
    if (left[i] !== right[i]) {
      return [
        `  line ${i + 1}`,
        `  committed: ${left[i] ?? "(missing)"}`,
        `  generated: ${right[i] ?? "(missing)"}`,
      ].join("\n");
    }
  }
  return "  (every line matches; only the newlines differ)";
}

if (process.argv.includes("--check")) {
  if (current !== text) {
    console.error(`atlas: out of date — ${OUT}. Run \`npm run docs:generate\`.`);
    console.error(firstDifference(current ?? "", text));
    process.exit(1);
  }
  console.log("atlas: up to date");
} else {
  writeFileSync(out, text);
  console.log(current === text ? `atlas: unchanged — ${OUT}` : `atlas: wrote ${OUT}`);
}
