#!/usr/bin/env node
/**
 * The parts of the documentation that are facts about the repository.
 *
 * Prose rots silently: nobody notices that "22,000 lines" became 31,000, or
 * that a list of CI gates lost the one added last month, and a reader who
 * checks one figure and finds it wrong stops trusting the page. So anything a
 * document states that the working tree already knows is generated between two
 * markers, and the words around it are not — each page keeps its argument, and
 * the bookkeeping stops being anyone's job.
 *
 *   node scripts/update-docs.mjs            rewrite every generated block
 *   node scripts/update-docs.mjs --check    fail if any is out of date
 *
 * `--check` is what CI runs, so a change that moves one of these facts has to
 * carry the regenerated block with it, the way a lockfile travels with a
 * dependency. Adding a new one is a `BLOCKS` entry plus the two markers in the
 * page: `<!-- generated:<id> -->` and `<!-- /generated:<id> -->`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { AREAS } from "./lib/areas.mjs";
import { ROOT, measure, n, read, switchCases } from "./lib/repo-stats.mjs";

function codeMap() {
  const rows = AREAS.map((area) => ({ ...area, ...measure(area) }));
  const counted = rows.filter((row) => row.unit === "lines");
  const totalLines = counted.reduce((sum, row) => sum + row.lines, 0);
  const totalFiles = counted.reduce((sum, row) => sum + row.files, 0);

  return [
    "| Where | Size | What lives there |",
    "| --- | --- | --- |",
    ...rows.map((row) =>
      `| \`${row.dir}\` | ${row.unit === "files" ? `${n(row.files)} files` : `${n(row.lines)} lines`} | ${row.what} |`,
    ),
    "",
    `**${n(totalLines)} lines of code in all**, across ${n(totalFiles)} source files.`,
  ];
}

/**
 * The IPC surface, read from the channel table rather than remembered.
 *
 * A hand-kept list of channels is a list that is wrong the week after somebody
 * adds one, and this is exactly the list a reader uses to decide whether a
 * thing they want is even possible from the renderer.
 */
function desktopIpc() {
  const source = read("apps/desktop/src/channels.ts");
  const channels = [...source.matchAll(/^\s{2}([a-zA-Z]+): "(weaveforge:[a-z-]+)",/gm)]
    .map((match) => ({ name: match[1], channel: match[2] }));
  // Members of the bridge object the preload exposes — one line each, and the
  // count is what the smoke test and the atlas both quote.
  const members = [...read("apps/desktop/src/preload.ts").matchAll(/^ {2}([a-zA-Z]+):/gm)].length;

  return [
    `${n(channels.length)} named channels, reached through the ${n(members)} members of the bridge`,
    "object the preload exposes:",
    "",
    ...channels.map((entry) => `- \`${entry.channel}\` — \`${entry.name}\``),
  ];
}

/** The tools an assistant may call, taken from the dispatch it is checked against. */
function mcpTools() {
  const relay = switchCases("apps/web/src/features/ai-assistant/infrastructure/mcp-browser-relay.ts");
  const reads = relay.filter((tool) => !tool.startsWith("propose_"));
  const proposals = relay.filter((tool) => tool.startsWith("propose_"));
  const workspace = [...read("apps/desktop/src/local-mcp.ts").matchAll(/name: "([a-z_]+)"/g)]
    .map((match) => match[1])
    .filter((name) => name !== "weaveforge-workspace");

  const list = (tools) => tools.map((tool) => `\`${tool}\``).join(", ");
  return [
    `**Read-only** (${n(reads.length)}): ${list(reads)}`,
    "",
    `**Proposal-only** (${n(proposals.length)}) — each saves an encrypted pending proposal, and`,
    `\`/ai-review\` is the only approval path: ${list(proposals)}`,
    "",
    `**The desktop workspace server** (${n(workspace.length)}): ${list(workspace)}`,
  ];
}

/** The gates `check:boundaries` actually runs today. */
function boundaryChecks() {
  const scripts = JSON.parse(read("package.json")).scripts;
  const names = (scripts["check:boundaries"] ?? "")
    .split("&&")
    .map((part) => part.trim().replace(/^npm run /, ""))
    .filter(Boolean);

  return [
    "| Gate | What it runs |",
    "| --- | --- |",
    ...names.map((name) => `| \`npm run ${name}\` | \`${scripts[name] ?? "—"}\` |`),
  ];
}

/**
 * Every generated block: which page it lives in, and what fills it.
 *
 * The id is in both markers so a page can hold several and a mismatched pair is
 * a visible mistake rather than a silently swallowed one.
 */
const BLOCKS = [
  { id: "code-map", doc: "docs/architecture-map.md", build: codeMap },
  { id: "desktop-ipc", doc: "docs/architecture-map.md", build: desktopIpc },
  { id: "mcp-tools", doc: "docs/MCP_IMPLEMENTATION.md", build: mcpTools },
  { id: "boundary-checks", doc: "docs/dev.md", build: boundaryChecks },
];

const NOTE = "<!-- Generated by scripts/update-docs.mjs — run `npm run docs:generate`. -->";

function fill(text, block, newline) {
  const start = `<!-- generated:${block.id} -->`;
  const end = `<!-- /generated:${block.id} -->`;
  const from = text.indexOf(start);
  const to = text.indexOf(end);
  if (from === -1 || to === -1) {
    throw new Error(`${block.doc} has no ${start} … ${end} block to fill.`);
  }
  const body = [start, "", NOTE, "", ...block.build(), "", end].join(newline);
  return text.slice(0, from) + body + text.slice(to + end.length);
}

const check = process.argv.includes("--check");
const stale = [];

for (const doc of new Set(BLOCKS.map((block) => block.doc))) {
  const full = path.join(ROOT, doc);
  const before = readFileSync(full, "utf8");
  const newline = before.includes("\r\n") ? "\r\n" : "\n";
  let after = before;
  for (const block of BLOCKS.filter((candidate) => candidate.doc === doc)) {
    after = fill(after, block, newline);
  }
  if (after === before) continue;
  if (check) stale.push(doc);
  else writeFileSync(full, after);
}

if (check) {
  if (stale.length === 0) {
    console.log("docs: generated blocks are up to date");
    process.exit(0);
  }
  console.error(`docs: out of date — ${stale.join(", ")}. Run \`npm run docs:generate\` and commit the result.`);
  process.exit(1);
}
console.log("docs: rewrote the generated blocks");
