// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { SupervisionScreen } from "@/features/org";

export default function GeneratedRoutePage() {
  return <SupervisionScreen />;
}
