// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { GraphScreen } from "@/features/relations";

export default function GeneratedRoutePage() {
  return <GraphScreen />;
}
