// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
"use client";

import { PapersScreen } from "@/features/papers";

export default function GeneratedRoutePage() {
  return <PapersScreen />;
}
