// AUTO-GENERATED by scripts/generate-deployment-registry.mjs — do not edit.
import { DashboardScreen as DashboardScreen } from "@/features/dashboard";
import { PapersScreen as PapersScreen } from "@/features/papers";
import { VaultScreen as VaultScreen } from "@/features/vault";
import { GraphScreen as GraphScreen } from "@/features/relations";
import { ListsScreen as ListsScreen } from "@/features/reading-lists";
import { ExperimentsScreen as ExperimentsScreen } from "@/features/experiments";
import { GitScreen as GitScreen } from "@/features/sync";
import { PlanScreen as PlanScreen } from "@/features/plan";
import { LogbookScreen as LogbookScreen } from "@/features/logbook";
import { ReportScreen as ReportScreen } from "@/features/report";
import { ReportOverleafScreen as ReportOverleafScreen } from "@/features/report";
import { SettingsScreen as SettingsScreen } from "@/features/settings";
import { SharedWithMeScreen as SharedWithMeScreen } from "@/features/sharing/ui/shared-with-me-screen";
import { SupervisionScreen as SupervisionScreen } from "@/features/org";
import { AiProposalReviewScreen as AiProposalReviewScreen } from "@/features/ai-assistant/ui/ai-proposal-review-screen";

export const GENERATED_ROUTE_COMPONENTS = { "/dashboard": DashboardScreen, "/papers": PapersScreen, "/notes": VaultScreen, "/graph": GraphScreen, "/lists": ListsScreen, "/experiments": ExperimentsScreen, "/git": GitScreen, "/plan": PlanScreen, "/log": LogbookScreen, "/report": ReportScreen, "/report/overleaf": ReportOverleafScreen, "/settings": SettingsScreen, "/shared": SharedWithMeScreen, "/supervision": SupervisionScreen, "/ai-review": AiProposalReviewScreen } as const;
