-- Rate-limit rows are internal implementation details of the share-link RPC.
-- Give them a stable key and make direct PostgREST access impossible.
alter table share_link_rate_limits
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.share_link_rate_limits'::regclass
      and contype = 'p'
  ) then
    alter table share_link_rate_limits add primary key (id);
  end if;
end
$$;

revoke all on table share_link_rate_limits from anon, authenticated;
alter table share_link_rate_limits enable row level security;
drop policy if exists "share_link_rate_limits_no_client_access" on share_link_rate_limits;
create policy "share_link_rate_limits_no_client_access" on share_link_rate_limits
  for all to anon, authenticated
  using (false)
  with check (false);

-- Invite codes are created and consumed only by server-side flows. Keep the
-- table explicitly deny-by-default so the intent is visible to advisors and
-- future maintainers.
revoke all on table org_invite_codes from anon, authenticated;
drop policy if exists "org_invite_codes_no_client_access" on org_invite_codes;
create policy "org_invite_codes_no_client_access" on org_invite_codes
  for all to anon, authenticated
  using (false)
  with check (false);
